FROM centos:6
MAINTAINER Asher Dawes asher.dawes@gmail.com

RUN dnf install \
     git \
     pkgconfig \
     automake \
     autoconf \
     ncurses-devel \
     python \
     python-zmq \
     wget \
     curl \
     gtest-devel \
     gcc \
     gcc-c++ \
     libtool \
     patch

